"""Real Vault provisioning step using Vault HTTP API directly (no hvac dep)."""

from __future__ import annotations

import os
from typing import Any

import httpx
import structlog

log = structlog.get_logger(__name__)


async def _vault_client() -> tuple[httpx.AsyncClient, str] | None:
    """Return (client, token). Tries token auth then AppRole."""
    addr = os.environ.get("VAULT_ADDR", "")
    if not addr:
        return None

    token = os.environ.get("VAULT_TOKEN", "")
    if not token:
        # Try AppRole login
        role_id = os.environ.get("VAULT_ROLE_ID", "")
        secret_id = os.environ.get("VAULT_SECRET_ID", "")
        if not role_id or not secret_id:
            return None
        async with httpx.AsyncClient(base_url=addr, timeout=15.0) as c:
            resp = await c.post(
                "/v1/auth/approle/login",
                json={"role_id": role_id, "secret_id": secret_id},
            )
            if resp.status_code != 200:
                log.error("vault approle login failed", status=resp.status_code)
                return None
            token = resp.json()["auth"]["client_token"]

    client = httpx.AsyncClient(
        base_url=addr,
        headers={"X-Vault-Token": token},
        timeout=15.0,
    )
    return client, token


async def run(profile: Any, topology: Any) -> "StepResult":  # type: ignore[name-defined]  # noqa: F821
    from sentinel.provisioning.runner import StepResult, StepStatus

    result = await _vault_client()
    if result is None:
        return StepResult(
            name="vault",
            status=StepStatus.SKIPPED,
            details={"reason": "VAULT_ADDR not configured"},
        )

    client, _token = result
    scope = topology.vault_scope
    policy_name = f"sentinel-{scope.replace('/', '-')}"

    # Build a least-privilege policy for this role
    policy_hcl = f"""
# Auto-generated by Sentinel Day One for {profile.full_name} ({profile.role})
path "{scope}/*" {{
  capabilities = ["read", "list"]
}}
path "{scope}/data/*" {{
  capabilities = ["read"]
}}
"""

    async with client:
        # Write the policy
        resp = await client.put(
            f"/v1/sys/policy/{policy_name}",
            json={"policy": policy_hcl},
        )
        if resp.status_code not in (200, 204):
            return StepResult(
                name="vault",
                status=StepStatus.FAILED,
                error=f"policy write failed: {resp.status_code} {resp.text[:200]}",
            )

        # Create a token bound to this policy
        resp = await client.post(
            "/v1/auth/token/create",
            json={
                "policies": [policy_name],
                "display_name": f"sentinel-{profile.employee_id}",
                "renewable": True,
                "ttl": "720h",
                "metadata": {
                    "employee": profile.employee_id,
                    "role": profile.role,
                    "created_by": "sentinel-day-one",
                },
            },
        )
        if resp.status_code != 200:
            return StepResult(
                name="vault",
                status=StepStatus.FAILED,
                error=f"token create failed: {resp.status_code}",
            )

    return StepResult(
        name="vault",
        status=StepStatus.SUCCESS,
        details={
            "scope": scope,
            "policy": policy_name,
            "note": "Token delivered via Vault UI or separate secure channel",
        },
    )
